[anykernel-kernelsu]
src.git = "https://github.com/Kernel-SU/AnyKernel3.git"
fetch.github = "Kernel-SU/AnyKernel3"

[anykernel-osm0sis]
src.git = "https://github.com/osm0sis/AnyKernel3.git"
fetch.github = "osm0sis/AnyKernel3"

[gcc-aarch64-linux-android]
src.git = "https://github.com/kindle4jerry/aarch64-linux-android-4.9-bakup.git"
fetch.github = "kindle4jerry/aarch64-linux-android-4.9-bakup"

[gcc-arm-linux-androideabi]
src.git = "https://github.com/KudProject/arm-linux-androideabi-4.9.git"
fetch.github = "KudProject/arm-linux-androideabi-4.9"

[kernelsu-stable]
src.git = "https://github.com/nitanmarcel/KernelSU-susfs"
fetch.github = "nitanmarcel/KernelSU-susfs"

[android-kernel-nothing-mt6878]
src.git = "https://github.com/nitanmarcel/android_kernel_6.1_nothing_mt6878"
src.branch = "mt6878/Tetris/u"
fetch.github = "nitanmarcel/android_kernel_6.1_nothing_mt6878"
git.fetchSubmodules = true
