# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  android-kernel-nothing-mt6878 = {
    pname = "android-kernel-nothing-mt6878";
    version = "c62ff8d7aa69f387471de054c64dd274b4554e29";
    src = fetchFromGitHub {
      owner = "nitanmarcel";
      repo = "android_kernel_6.1_nothing_mt6878";
      rev = "c62ff8d7aa69f387471de054c64dd274b4554e29";
      fetchSubmodules = true;
      sha256 = "sha256-ZHPDi2JA/bwE3mLyND5G02P1MSKZrFcupoHEphmnLcQ=";
    };
    date = "2024-08-21";
  };
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
      fetchSubmodules = false;
      sha256 = "sha256-QJS4+1teNcgUOy2gD+KuoEG/9pUNd/6uSH84AkAlVoQ=";
    };
    date = "2023-10-30";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "c55d63f39335b68116fa820eee221b61bc233fe3";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "c55d63f39335b68116fa820eee221b61bc233fe3";
      fetchSubmodules = false;
      sha256 = "sha256-qJu+P3oAON6EWKk3Hye9AePhgz495zNkYBRPnHmi9MU=";
    };
    date = "2024-05-09";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "149df80d4884725442e02d6a66916fc4b4486fd5";
    src = fetchFromGitHub {
      owner = "nitanmarcel";
      repo = "KernelSU-susfs";
      rev = "149df80d4884725442e02d6a66916fc4b4486fd5";
      fetchSubmodules = false;
      sha256 = "sha256-rPRj8CyrQXxtmashFGF1vapzTMWrsdxbrAoTZarc6Ns=";
    };
    date = "2024-08-21";
  };
}
