name: 'Auto update packages'
on:
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Install nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = i686-linux aarch64-linux arm-linux
      - name: Build nix packages
        run: |
          cat > secrets.toml <<EOF
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF

          nix flake update
          nix run .#nvfetcher

          rm -f secrets.toml

      - name: Commit back to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'auto: update packages'
